# Backend server configuration
# Make sure to change these values in production
jwt_secret: "a_very_random_and_secure_secret_key_change_me"

# Default admin user
# If the user exists, the password will be updated on startup.
# If the user does not exist, a new admin user will be created.
admin:
  username: "admin"
  password: "new_strong_password"